// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4dJROTtuq61NtXGDuC5KARC5NRLpMiSU',
    appId: '1:54863733435:web:bca5327696cac75a18ff9e',
    messagingSenderId: '54863733435',
    projectId: 'auth-modul-3a06a',
    authDomain: 'auth-modul-3a06a.firebaseapp.com',
    storageBucket: 'auth-modul-3a06a.firebasestorage.app',
    measurementId: 'G-86YQJDEBJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYMAeZZUMF4FWe8OSr2Sk4FrsGHlKQhi4',
    appId: '1:54863733435:android:2c072b06665a953818ff9e',
    messagingSenderId: '54863733435',
    projectId: 'auth-modul-3a06a',
    storageBucket: 'auth-modul-3a06a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-lURudo0pub2BSSWWgc1XQq0nnCnLpP0',
    appId: '1:54863733435:ios:ee97283ff156c0bd18ff9e',
    messagingSenderId: '54863733435',
    projectId: 'auth-modul-3a06a',
    storageBucket: 'auth-modul-3a06a.firebasestorage.app',
    iosBundleId: 'com.example.ppbFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-lURudo0pub2BSSWWgc1XQq0nnCnLpP0',
    appId: '1:54863733435:ios:ee97283ff156c0bd18ff9e',
    messagingSenderId: '54863733435',
    projectId: 'auth-modul-3a06a',
    storageBucket: 'auth-modul-3a06a.firebasestorage.app',
    iosBundleId: 'com.example.ppbFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4dJROTtuq61NtXGDuC5KARC5NRLpMiSU',
    appId: '1:54863733435:web:62a1c328785ad07d18ff9e',
    messagingSenderId: '54863733435',
    projectId: 'auth-modul-3a06a',
    authDomain: 'auth-modul-3a06a.firebaseapp.com',
    storageBucket: 'auth-modul-3a06a.firebasestorage.app',
    measurementId: 'G-SFGC4XFYKB',
  );

}